//! Fixture loader — reads pre-baked `stream.jsonl` and the shared UX-constants
//! TOML without pulling in serde. Both files are generated by xtask so we can
//! make very tight assumptions about formatting.

use std::fs;
use std::path::PathBuf;
use std::time::Duration;

use runtime_core::api::GpsSample;

use crate::FixtureFrame;
use crate::FIXTURE_VIEWPORT;

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RideSample {
    pub sample: GpsSample,
    pub time_offset_ms: i64,
}

#[derive(Debug, Clone)]
pub struct RideScenario {
    pub name: &'static str,
    pub samples: Vec<RideSample>,
}

impl RideScenario {
    /// Emit one `FixtureFrame` per fixture sample with the inter-sample delta
    /// as `dt`. The first frame's `dt` is 16 ms so the runtime can initialize.
    pub fn to_frames(&self) -> Vec<FixtureFrame> {
        let mut out = Vec::with_capacity(self.samples.len());
        for (index, ride_sample) in self.samples.iter().enumerate() {
            let dt = if index == 0 {
                Duration::from_millis(16)
            } else {
                let prev_ms = self.samples[index - 1].time_offset_ms;
                let delta_ms = (ride_sample.time_offset_ms - prev_ms).max(1) as u64;
                Duration::from_millis(delta_ms)
            };
            out.push(FixtureFrame {
                dt,
                viewport: FIXTURE_VIEWPORT,
                gps: Some(ride_sample.sample),
                touch: None,
            });
        }
        out
    }

    /// Slice a scenario by inclusive time range in milliseconds.
    pub fn slice_by_time(&self, start_ms: i64, end_ms: i64) -> RideScenario {
        let samples = self
            .samples
            .iter()
            .filter(|sample| sample.time_offset_ms >= start_ms && sample.time_offset_ms <= end_ms)
            .copied()
            .collect();
        RideScenario {
            name: self.name,
            samples,
        }
    }
}

/// Load the helsinki-gravel ride scenario. Panics if the fixture is missing —
/// regenerate with `cargo run -p xtask --bin gen-gps-fixtures`.
pub fn load_gps_stream(name: &'static str) -> RideScenario {
    let path = workspace_root()
        .join("parity-fixtures/data")
        .join(name)
        .join("stream.jsonl");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    let samples = parse_stream_jsonl(&text)
        .unwrap_or_else(|error| panic!("failed to parse {}: {error}", path.display()));
    RideScenario { name, samples }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct UxConstants {
    pub enter_moving_kph: f32,
    pub exit_moving_kph: f32,
    pub moving_dwell: Duration,
    pub recenter_inactivity: Duration,
    pub north_override_timeout: Duration,
    pub double_tap_window: Duration,
    pub off_route_distance_m: f64,
    pub off_route_dwell: Duration,
    pub typeahead_debounce: Duration,
    pub stationary_view_radius_m: f64,
    pub recents_page_size: u32,
}

/// Load the shared UX constants. Panics if the file is missing or a key is
/// unparseable — the TOML ships in-tree so the error is always a developer
/// mistake.
pub fn load_ux_constants() -> UxConstants {
    let path = workspace_root().join("parity-fixtures/data/ux-constants.toml");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    parse_ux_constants(&text)
        .unwrap_or_else(|error| panic!("failed to parse {}: {error}", path.display()))
}

fn parse_stream_jsonl(text: &str) -> Result<Vec<RideSample>, String> {
    text.lines()
        .filter(|line| !line.trim().is_empty())
        .map(parse_stream_line)
        .collect()
}

fn parse_stream_line(line: &str) -> Result<RideSample, String> {
    let lat = read_number_field(line, "lat_deg")?;
    let lon = read_number_field(line, "lon_deg")?;
    let speed = read_number_field(line, "speed_mps")? as f32;
    let course = read_number_field(line, "course_rad")? as f32;
    let accuracy = read_number_field(line, "accuracy_m")? as f32;
    let time_offset_ms = read_number_field(line, "t_ms")? as i64;
    Ok(RideSample {
        sample: GpsSample {
            lat_deg: lat,
            lon_deg: lon,
            speed_mps: speed,
            course_rad: Some(course),
            horizontal_accuracy_m: Some(accuracy),
        },
        time_offset_ms,
    })
}

fn read_number_field(line: &str, key: &str) -> Result<f64, String> {
    let needle = format!("\"{key}\":");
    let start = line
        .find(&needle)
        .ok_or_else(|| format!("key {key} not found in line"))?;
    let after = &line[start + needle.len()..];
    let end = after
        .find(|c: char| c == ',' || c == '}')
        .ok_or_else(|| format!("key {key} not terminated"))?;
    after[..end]
        .trim()
        .parse::<f64>()
        .map_err(|e| format!("bad number for {key}: {e}"))
}

const KNOWN_UX_KEYS: &[&str] = &[
    "enter_moving_kph",
    "exit_moving_kph",
    "moving_dwell_ms",
    "recenter_inactivity_ms",
    "north_override_timeout_ms",
    "double_tap_window_ms",
    "off_route_distance_m",
    "off_route_dwell_ms",
    "typeahead_debounce_ms",
    "stationary_view_radius_m",
    "recents_page_size",
];

fn parse_ux_constants(text: &str) -> Result<UxConstants, String> {
    // Pre-scan: every key present in the file must be listed in KNOWN_UX_KEYS.
    // A typo in the TOML or a key added to the file but not to the struct
    // should fail loudly, not silently default to 0.
    for line in text.lines() {
        let clean = line.split('#').next().unwrap_or("").trim();
        if clean.is_empty() || clean.starts_with('[') {
            continue;
        }
        let Some((key, _value)) = clean.split_once('=') else { continue };
        let key = key.trim();
        if !KNOWN_UX_KEYS.contains(&key) {
            return Err(format!(
                "unknown ux-constants key `{key}`; add it to KNOWN_UX_KEYS + UxConstants if intentional"
            ));
        }
    }

    let read_f64 = |key: &str| -> Result<f64, String> {
        for line in text.lines() {
            let line = line.split('#').next().unwrap_or("").trim();
            if let Some(rest) = line.strip_prefix(&format!("{key} ")) {
                let value = rest.trim().trim_start_matches('=').trim();
                return value
                    .parse::<f64>()
                    .map_err(|e| format!("bad number for {key}: {e}"))
            }
            if let Some(rest) = line.strip_prefix(&format!("{key}=")) {
                return rest
                    .trim()
                    .parse::<f64>()
                    .map_err(|e| format!("bad number for {key}: {e}"))
            }
        }
        Err(format!("key {key} not found"))
    };

    let read_duration_ms = |key: &str| -> Result<Duration, String> {
        Ok(Duration::from_millis(read_f64(key)? as u64))
    };

    Ok(UxConstants {
        enter_moving_kph: read_f64("enter_moving_kph")? as f32,
        exit_moving_kph: read_f64("exit_moving_kph")? as f32,
        moving_dwell: read_duration_ms("moving_dwell_ms")?,
        recenter_inactivity: read_duration_ms("recenter_inactivity_ms")?,
        north_override_timeout: read_duration_ms("north_override_timeout_ms")?,
        double_tap_window: read_duration_ms("double_tap_window_ms")?,
        off_route_distance_m: read_f64("off_route_distance_m")?,
        off_route_dwell: read_duration_ms("off_route_dwell_ms")?,
        typeahead_debounce: read_duration_ms("typeahead_debounce_ms")?,
        stationary_view_radius_m: read_f64("stationary_view_radius_m")?,
        recents_page_size: read_f64("recents_page_size")? as u32,
    })
}

fn workspace_root() -> PathBuf {
    // parity-fixtures/src/loader.rs — go up twice.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("parity-fixtures must live inside the workspace")
        .to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_ux_constants_file() {
        let constants = load_ux_constants();
        assert_eq!(constants.enter_moving_kph, 0.5);
        assert_eq!(constants.exit_moving_kph, 0.3);
        assert_eq!(constants.moving_dwell, Duration::from_millis(2000));
        assert_eq!(constants.recenter_inactivity, Duration::from_millis(1300));
        assert_eq!(constants.recents_page_size, 20);
    }

    #[test]
    fn loads_helsinki_gravel_ride() {
        let scenario = load_gps_stream("helsinki-gravel");
        assert!(!scenario.samples.is_empty(), "fixture should not be empty");
        assert_eq!(scenario.samples[0].time_offset_ms, 0);
        assert!(scenario.samples.last().unwrap().time_offset_ms > 1_000);
    }

    #[test]
    fn to_frames_has_dt_matching_time_deltas() {
        let scenario = load_gps_stream("helsinki-gravel");
        let frames = scenario.to_frames();
        assert_eq!(frames.len(), scenario.samples.len());
        assert_eq!(frames[0].dt, Duration::from_millis(16));
        // The second frame dt = difference between first two samples.
        let expected =
            Duration::from_millis((scenario.samples[1].time_offset_ms) as u64);
        assert_eq!(frames[1].dt, expected);
    }
}
