package me.fiksu.esp32map.companion.integration.i18n

import android.content.Context
import android.util.Log
import java.util.Locale

/**
 * Companion-Android i18n runtime. Loads JSON catalogs generated by
 * `cargo xtask i18n-gen` from the app's res/raw assets and exposes
 * `Strings.t(key, args)` for localized lookups with ICU placeholder
 * formatting.
 *
 * Active locale derivation:
 *  1. CompanionSettings.language if set to a concrete locale
 *  2. otherwise Locale.getDefault() matched against shipped locales
 *  3. otherwise the source locale ("en")
 *
 * Mirrors the TS/Swift runtimes so every platform's `cueMessage(event, …)`
 * resolves to the same text.
 */
enum class AppLanguagePref { SYSTEM, EN, FI }
enum class DistanceUnitPref { SYSTEM, METRIC, IMPERIAL }
enum class DistanceMode { METRIC, IMPERIAL }

enum class SupportedLocale(val tag: String) {
    EN("en"),
    FI("fi");

    companion object {
        val source = EN

        fun fromTag(tag: String): SupportedLocale? =
            entries.firstOrNull { it.tag.equals(tag, ignoreCase = true) }
    }
}

object Strings {
    private const val TAG = "I18n"
    private val catalogs: MutableMap<SupportedLocale, Map<String, String>> = mutableMapOf()
    @Volatile
    private var active: SupportedLocale = SupportedLocale.EN

    val activeLocale: SupportedLocale get() = active
    val activeBcp47: String get() = active.tag

    /** Initialize the runtime by loading every catalog from res/raw. */
    fun bootstrap(context: Context) {
        val resources = context.resources
        for (locale in SupportedLocale.entries) {
            // res/raw IDs are derived from the resource name with hyphens
            // replaced; we ship `messages_<locale>.json` so the lookup is
            // straightforward.
            val resId = resources.getIdentifier(
                "messages_${locale.tag}",
                "raw",
                context.packageName,
            )
            if (resId == 0) {
                Log.w(TAG, "missing i18n catalog raw resource for ${locale.tag}")
                catalogs[locale] = emptyMap()
                continue
            }
            try {
                resources.openRawResource(resId).use { stream ->
                    val text = stream.bufferedReader().readText()
                    catalogs[locale] = parseFlatJson(text)
                }
                Log.i(TAG, "loaded ${catalogs[locale]?.size ?: 0} keys for ${locale.tag}")
            } catch (e: Exception) {
                Log.e(TAG, "failed to read catalog for ${locale.tag}", e)
                catalogs[locale] = emptyMap()
            }
        }
    }

    fun setActiveLocale(locale: SupportedLocale) {
        active = locale
    }

    fun resolveLocale(preference: AppLanguagePref): SupportedLocale = when (preference) {
        AppLanguagePref.EN -> SupportedLocale.EN
        AppLanguagePref.FI -> SupportedLocale.FI
        AppLanguagePref.SYSTEM -> {
            val tag = Locale.getDefault().language
            SupportedLocale.fromTag(tag) ?: SupportedLocale.source
        }
    }

    fun resolveDistanceUnit(preference: DistanceUnitPref): DistanceMode = when (preference) {
        DistanceUnitPref.METRIC -> DistanceMode.METRIC
        DistanceUnitPref.IMPERIAL -> DistanceMode.IMPERIAL
        DistanceUnitPref.SYSTEM -> {
            val tag = Locale.getDefault().country.uppercase()
            // Apple/Google convention: only US, LR, and MM use imperial.
            if (tag == "US" || tag == "LR" || tag == "MM") DistanceMode.IMPERIAL
            else DistanceMode.METRIC
        }
    }

    /** Translate `key` for the active locale. Falls back to source locale,
     *  then to the key itself. */
    fun t(key: String, args: Map<String, Any> = emptyMap()): String =
        format(active, key, args)

    /** Translate using a specific locale — used by parity tests. */
    fun tIn(locale: SupportedLocale, key: String, args: Map<String, Any> = emptyMap()): String =
        format(locale, key, args)

    private fun format(locale: SupportedLocale, key: String, args: Map<String, Any>): String {
        val template = catalogs[locale]?.get(key)
            ?: catalogs[SupportedLocale.source]?.get(key)
            ?: key
        if (args.isEmpty()) return template
        return try {
            MessageFormat.format(template, args, Locale(locale.tag))
        } catch (_: Exception) {
            template
        }
    }

    /** Tiny tolerant parser for the flat `{ "key": "value", ... }` shape
     *  emitted by xtask i18n-gen. We don't bring in Gson here to keep this
     *  module standalone for tests; if the file shape ever grows, swap to
     *  the project's existing Gson dep. */
    private fun parseFlatJson(text: String): Map<String, String> {
        val out = mutableMapOf<String, String>()
        val chars = text.toCharArray()
        var i = 0
        // Skip until first '{'
        while (i < chars.size && chars[i] != '{') i++
        if (i >= chars.size) return out
        i++
        while (i < chars.size) {
            // Skip whitespace + commas
            while (i < chars.size && (chars[i].isWhitespace() || chars[i] == ',')) i++
            if (i >= chars.size || chars[i] == '}') break
            if (chars[i] != '"') { i++; continue }
            val (key, ki) = readString(chars, i)
            i = ki
            // Skip whitespace + colon
            while (i < chars.size && (chars[i].isWhitespace() || chars[i] == ':')) i++
            if (i >= chars.size || chars[i] != '"') break
            val (value, vi) = readString(chars, i)
            out[key] = value
            i = vi
        }
        return out
    }

    private fun readString(chars: CharArray, start: Int): Pair<String, Int> {
        // chars[start] is '"'; read until unescaped closing quote.
        val sb = StringBuilder()
        var i = start + 1
        while (i < chars.size) {
            val c = chars[i]
            if (c == '\\' && i + 1 < chars.size) {
                val next = chars[i + 1]
                sb.append(
                    when (next) {
                        '"' -> '"'
                        '\\' -> '\\'
                        '/' -> '/'
                        'n' -> '\n'
                        'r' -> '\r'
                        't' -> '\t'
                        else -> next
                    }
                )
                i += 2
            } else if (c == '"') {
                return sb.toString() to (i + 1)
            } else {
                sb.append(c)
                i++
            }
        }
        return sb.toString() to chars.size
    }
}
