pub mod app;
pub mod board_config;
pub mod display;
pub mod esp_idf;
pub mod esp_idf_ble;
pub mod framebuffer;
#[cfg(all(target_os = "espidf", esp32p4))]
pub mod hosted_ble;
pub mod gps;
pub mod input_bridge;
pub mod map_source;
#[cfg(target_os = "espidf")]
pub mod i2c_scan;
#[cfg(target_os = "espidf")]
pub mod mipi_dsi;
#[cfg(target_os = "espidf")]
pub mod touch_gt911;
pub mod platform;
pub mod route_sync;
pub mod route_sync_ble;
pub mod settings;
pub mod touch;
pub mod world_buffer;
