[package]
name = "map-runtime"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["runtime-core/std"]

[dependencies]
runtime-core = { path = "../runtime-core", default-features = false }
hashbrown = { version = "0.15", default-features = false, features = ["default-hasher"] }
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
