// Companion-iOS i18n runtime. Loads the JSON catalogs generated by
// `cargo xtask i18n-gen` (bundled under Resources/Messages/) and exposes
// `T.string(_:)` for translating keys with optional ICU placeholders.
//
// Active locale derivation:
//   1. CompanionSettings.language if set to a concrete locale
//   2. otherwise Bundle.main.preferredLocalizations[0]
//   3. otherwise the source locale ("en")
//
// Mirrors the TypeScript runtime in companion-web/src/i18n/index.ts so
// every platform's `cueMessage(event, …)` resolves to the same text.

import Foundation
import os.log

enum AppLanguage: String, Codable, CaseIterable {
    case system
    case ar, bn, de, en, es, fa, fi, fr
    case hi, id, ja, mr, pcm, pt, ru, ur, zh
}

enum DistanceUnitPref: String, Codable, CaseIterable {
    case system
    case metric
    case imperial
}

enum SupportedLocale: String, CaseIterable {
    case ar, bn, de, en, es, fa, fi, fr
    case hi, id, ja, mr, pcm, pt, ru, ur, zh

    static let source: SupportedLocale = .en

    /// Native-language picker label. Always presented in the language's
    /// own native form regardless of active locale, matching how iOS
    /// Settings shows language names.
    var nativeName: String {
        switch self {
        case .ar: return "العربية"
        case .bn: return "বাংলা"
        case .de: return "Deutsch"
        case .en: return "English"
        case .es: return "Español"
        case .fa: return "فارسی"
        case .fi: return "Suomi"
        case .fr: return "Français"
        case .hi: return "हिन्दी"
        case .id: return "Bahasa Indonesia"
        case .ja: return "日本語"
        case .mr: return "मराठी"
        case .pcm: return "Naijá"
        case .pt: return "Português"
        case .ru: return "Русский"
        case .ur: return "اردو"
        case .zh: return "中文"
        }
    }

    /// Right-to-left script. Mirror of catalog.config.json:localeOptions.
    var isRtl: Bool {
        switch self {
        case .ar, .fa, .ur: return true
        default: return false
        }
    }
}

/// Translation namespace. Use `T.string("key")` everywhere user-visible
/// text appears.
enum T {
    private static let log = Logger(
        subsystem: "me.fiksu.esp32map.companion.ios",
        category: "i18n"
    )

    private static var catalogs: [SupportedLocale: [String: String]] = loadCatalogs()
    private static var active: SupportedLocale = .en

    static var activeLocale: SupportedLocale { active }

    /// BCP-47 tag of the active locale — fed to AVSpeechSynthesisVoice.
    static var activeBcp47: String { active.rawValue }

    /// True when the active locale is right-to-left. Driven into
    /// SwiftUI via `.environment(\.layoutDirection, T.activeLayoutDirection)`
    /// at the root view; SwiftUI flips horizontal stacks, paddings,
    /// chevrons and so on automatically once that environment value is
    /// set.
    static var isRtl: Bool { active.isRtl }

    static func setActiveLocale(_ locale: SupportedLocale) {
        active = locale
    }

    /// Resolve a user preference to a shipped locale.
    static func resolveLocale(_ preference: AppLanguage) -> SupportedLocale {
        if preference == .system {
            for tag in Bundle.main.preferredLocalizations {
                let primary = tag.lowercased().split(separator: "-").first.map(String.init) ?? ""
                if let match = SupportedLocale(rawValue: primary) { return match }
            }
            return .source
        }
        // AppLanguage and SupportedLocale share the same raw values for
        // every concrete case, so the rawValue lookup never returns nil
        // here — but fall back to source defensively if the unions ever
        // drift apart.
        return SupportedLocale(rawValue: preference.rawValue) ?? .source
    }

    /// Resolve the distance-unit preference. `.system` maps en-US/en-LR/my
    /// to imperial, everything else to metric — matches the Apple default
    /// for navigation apps.
    static func resolveDistanceUnit(_ preference: DistanceUnitPref) -> DistanceMode {
        switch preference {
        case .metric: return .metric
        case .imperial: return .imperial
        case .system:
            let tag = Locale.current.identifier.lowercased()
            if tag.hasPrefix("en_us") || tag.hasPrefix("en-us")
                || tag.hasPrefix("en_lr") || tag.hasPrefix("en-lr")
                || tag.hasPrefix("my") {
                return .imperial
            }
            return .metric
        }
    }

    /// Translate `key` for the active locale. ICU placeholders in the
    /// template are filled from `args`. Falls back to the source locale's
    /// catalog, then to the key itself.
    static func string(_ key: String, _ args: [String: MessageValue] = [:]) -> String {
        let template = catalogs[active]?[key]
            ?? catalogs[.source]?[key]
            ?? key
        if args.isEmpty { return template }
        return MessageFormat.format(template, values: args, locale: Locale(identifier: activeBcp47))
    }

    /// Translate using a specific locale instead of the active one — used
    /// by parity tests that need to render English regardless of runtime
    /// state.
    static func stringIn(_ locale: SupportedLocale, _ key: String, _ args: [String: MessageValue] = [:]) -> String {
        let template = catalogs[locale]?[key] ?? catalogs[.source]?[key] ?? key
        if args.isEmpty { return template }
        return MessageFormat.format(template, values: args, locale: Locale(identifier: locale.rawValue))
    }

    private static func loadCatalogs() -> [SupportedLocale: [String: String]] {
        var out: [SupportedLocale: [String: String]] = [:]
        for locale in SupportedLocale.allCases {
            // Resources/Messages/<locale>.json is bundled flat after build,
            // so look up by name only.
            guard let url = Bundle.main.url(forResource: locale.rawValue, withExtension: "json", subdirectory: "Messages")
                ?? Bundle.main.url(forResource: locale.rawValue, withExtension: "json")
            else {
                log.error("missing i18n catalog for locale \(locale.rawValue, privacy: .public)")
                out[locale] = [:]
                continue
            }
            do {
                let data = try Data(contentsOf: url)
                let decoded = try JSONDecoder().decode([String: String].self, from: data)
                out[locale] = decoded
                log.info("loaded \(decoded.count) keys for \(locale.rawValue, privacy: .public)")
            } catch {
                log.error("failed to load \(url.lastPathComponent, privacy: .public): \(error.localizedDescription, privacy: .public)")
                out[locale] = [:]
            }
        }
        return out
    }
}

enum DistanceMode {
    case metric
    case imperial
}
