// Parity test: every platform's `cueMessage(event, distanceMode="metric")`
// must produce the structured (key, values) tuple recorded in
// `i18n/parity/cue-en-snapshots.json`. The fixture is generated by
// `cargo xtask i18n-gen` so adding a new event in EN shows up here too.

import { describe, expect, it } from "vitest";
import fixture from "../../../i18n/parity/cue-en-snapshots.json";
import { tIn } from "../i18n/index.js";
import { type CueEvent, cueMessage } from "../integrations/cues/CueEngine.js";

type Row = {
  event: CueEvent;
  expected: { key: string; values: Record<string, unknown> };
};

describe("cueMessage parity against i18n/parity/cue-en-snapshots.json", () => {
  for (const row of fixture.rows as Row[]) {
    const label = `${row.event.kind}${
      "turnKind" in row.event ? `.${(row.event as { turnKind: string }).turnKind}` : ""
    }`;
    it(`produces expected structure for ${label}`, () => {
      const msg = cueMessage(row.event, "metric");
      expect(msg.key).toBe(row.expected.key);
      expect(msg.values).toEqual(row.expected.values);
    });
  }

  it("EN-resolves every fixture row to a non-empty string", () => {
    for (const row of fixture.rows as Row[]) {
      const msg = cueMessage(row.event, "metric");
      const text = tIn("en", msg.key, msg.values as Record<string, string | number>);
      expect(text.length).toBeGreaterThan(0);
      expect(text).not.toMatch(/{[a-z]+}/i); // no unfilled placeholders
    }
  });
});
