#!/usr/bin/env bash
set -euo pipefail

# Keep espup artifacts and export script in persistent config volume.
ESP_CONFIG_DIR="${HOME}/.config/esp"
ESP_EXPORT_PERSIST="${ESP_CONFIG_DIR}/export-esp.sh"
ESP_EXPORT_HOME="${HOME}/export-esp.sh"
mkdir -p "${ESP_CONFIG_DIR}"

# Restore export script into $HOME if persisted from a previous container.
if [ -f "${ESP_EXPORT_PERSIST}" ] && [ ! -f "${ESP_EXPORT_HOME}" ]; then
  cp "${ESP_EXPORT_PERSIST}" "${ESP_EXPORT_HOME}"
fi

# Install Espressif toolchain only when no export script exists anywhere.
if [ ! -f "${ESP_EXPORT_HOME}" ] && [ ! -f "${ESP_EXPORT_PERSIST}" ]; then
  espup install
fi

# Persist export script generated by espup for future rebuilds.
if [ -f "${ESP_EXPORT_HOME}" ] && [ ! -f "${ESP_EXPORT_PERSIST}" ]; then
  cp "${ESP_EXPORT_HOME}" "${ESP_EXPORT_PERSIST}"
fi

# Ensure shell sessions load ESP exports when available.
if [ -f "${ESP_EXPORT_HOME}" ] && ! grep -q 'source "$HOME/export-esp.sh"' "${HOME}/.bashrc"; then
  printf '\nsource "$HOME/export-esp.sh"\n' >> "${HOME}/.bashrc"
fi

# In this devcontainer, ~/.cargo may be mounted as root-owned. Use writable CARGO_HOME.
if ! [ -w "${HOME}/.cargo" ]; then
  if ! grep -q 'export CARGO_HOME=/usr/local/cargo' "${HOME}/.bashrc"; then
    printf '\nexport CARGO_HOME=/usr/local/cargo\n' >> "${HOME}/.bashrc"
    printf 'export PATH="$CARGO_HOME/bin:$PATH"\n' >> "${HOME}/.bashrc"
  fi
  export CARGO_HOME=/usr/local/cargo
  export PATH="$CARGO_HOME/bin:$PATH"
fi

# Emulator toolchain dependency for `cargo xtask emu`.
if ! command -v wasm-pack >/dev/null 2>&1; then
  CARGO_HOME="${CARGO_HOME:-/usr/local/cargo}" cargo install wasm-pack
fi

# Install emulator web dependencies for the first `cargo xtask emu` run.
if [ -f /work/emulator/web/package-lock.json ] && [ ! -d /work/emulator/web/node_modules ]; then
  (cd /work/emulator/web && npm ci)
fi

# Keep local bun usable in future shells when present.
if [ -x "${HOME}/.bun/bin/bun" ] && ! grep -q 'export PATH="$HOME/.bun/bin:$PATH"' "${HOME}/.bashrc"; then
  printf '\nexport PATH="$HOME/.bun/bin:$PATH"\n' >> "${HOME}/.bashrc"
fi

# Keep git global config in a persistent mounted directory.
mkdir -p "${HOME}/.config/git"
if [ ! -f "${HOME}/.config/git/config" ]; then
  touch "${HOME}/.config/git/config"
fi
if [ -f "${HOME}/.gitconfig" ] && [ ! -s "${HOME}/.config/git/config" ]; then
  cp "${HOME}/.gitconfig" "${HOME}/.config/git/config"
fi

# Persisted SSH directory should keep secure permissions for OpenSSH.
mkdir -p "${HOME}/.ssh"
chmod 700 "${HOME}/.ssh"
find "${HOME}/.ssh" -type f -name "id_*" -exec chmod 600 {} \;

# Lex code viewer: initialize and start if mounted at /opt/lex.
if [ -f /opt/lex/server.ts ] && command -v bun >/dev/null 2>&1; then
  # Install dependencies if missing
  if [ ! -d /opt/lex/node_modules ]; then
    (cd /opt/lex && bun install)
  fi

  # Fix node-pty spawn-helper permissions if needed
  find /opt/lex/node_modules/node-pty/prebuilds -name "spawn-helper" -exec chmod +x {} \; 2>/dev/null || true

  # Load env from persistent home if available
  LEX_ENV="${HOME}/.config/lex/.env"

  if command -v tmux >/dev/null 2>&1; then
    tmux new-session -d -s lex \
      "cd /opt/lex && set -a && [ -f '${LEX_ENV}' ] && source '${LEX_ENV}'; set +a && bun run server.ts --port 3024 --root /work" \
      2>/dev/null || true
    echo "Lex code viewer started on port 3024"
  fi
fi

# Start code-server for browser-based VS Code access (only when password is configured).
if [ -n "${CODE_SERVER_PASSWORD:-}" ] && command -v code-server >/dev/null 2>&1 && command -v tmux >/dev/null 2>&1; then
  tmux new-session -d -s code-server \
    "PASSWORD='${CODE_SERVER_PASSWORD}' code-server --bind-addr 0.0.0.0:8449 --auth password /work" \
    2>/dev/null || true
  echo "Code Server started on port 8449"
fi
