#!/usr/bin/env bash
set -euo pipefail

# Load shared env from repo root .env (API keys, etc.)
if [ -f /work/.env ]; then
  set -a
  source /work/.env
  set +a
fi

# Keep espup artifacts and export script in persistent config volume.
ESP_CONFIG_DIR="${HOME}/.config/esp"
ESP_EXPORT_PERSIST="${ESP_CONFIG_DIR}/export-esp.sh"
ESP_EXPORT_HOME="${HOME}/export-esp.sh"
mkdir -p "${ESP_CONFIG_DIR}"

# Restore export script into $HOME if persisted from a previous container.
if [ -f "${ESP_EXPORT_PERSIST}" ] && [ ! -f "${ESP_EXPORT_HOME}" ]; then
  cp "${ESP_EXPORT_PERSIST}" "${ESP_EXPORT_HOME}"
fi

# Install Espressif toolchain only when no export script exists anywhere.
# `--targets esp32p4 --esp-riscv-gcc` installs only the RISC-V toolchain needed
# by the Waveshare ESP32-P4-Module-DEV-KIT; the Xtensa toolchain is not used.
if [ ! -f "${ESP_EXPORT_HOME}" ] && [ ! -f "${ESP_EXPORT_PERSIST}" ]; then
  espup install --targets esp32p4 --esp-riscv-gcc --export-file "${ESP_EXPORT_HOME}"
fi

# Persist export script generated by espup for future rebuilds.
if [ -f "${ESP_EXPORT_HOME}" ] && [ ! -f "${ESP_EXPORT_PERSIST}" ]; then
  cp "${ESP_EXPORT_HOME}" "${ESP_EXPORT_PERSIST}"
fi

# Ensure shell sessions load ESP exports when available.
if [ -f "${ESP_EXPORT_HOME}" ] && ! grep -q 'source "$HOME/export-esp.sh"' "${HOME}/.bashrc"; then
  printf '\nsource "$HOME/export-esp.sh"\n' >> "${HOME}/.bashrc"
fi

# In this devcontainer, ~/.cargo may be mounted as root-owned. Use writable CARGO_HOME.
if ! [ -w "${HOME}/.cargo" ]; then
  if ! grep -q 'export CARGO_HOME=/usr/local/cargo' "${HOME}/.bashrc"; then
    printf '\nexport CARGO_HOME=/usr/local/cargo\n' >> "${HOME}/.bashrc"
    printf 'export PATH="$CARGO_HOME/bin:$PATH"\n' >> "${HOME}/.bashrc"
  fi
  export CARGO_HOME=/usr/local/cargo
  export PATH="$CARGO_HOME/bin:$PATH"
fi

# Device bring-up toolchain for `cargo xtask bundle-device` / `deploy-device`.
# Nightly is required because `riscv32imafc-esp-espidf` is a tier-3 target
# and must be built with `-Zbuild-std=std,panic_abort`.
if ! rustup toolchain list 2>/dev/null | grep -q '^nightly-'; then
  rustup toolchain install nightly --component rust-src
fi
# `ldproxy` wraps the ESP linker; `espflash` talks to the bootloader over USB.
if ! command -v ldproxy >/dev/null 2>&1 || ! command -v espflash >/dev/null 2>&1; then
  CARGO_HOME="${CARGO_HOME:-/usr/local/cargo}" cargo install ldproxy espflash --locked
fi
# ESP-IDF's `idf_tools.py install-python-env` needs the venv module.
if ! python3 -c 'import venv, ensurepip' >/dev/null 2>&1; then
  sudo apt-get update -qq && sudo apt-get install -y -qq python3-venv
fi

# Emulator toolchain dependency for `cargo xtask emu`.
# wasm-pack 0.14 pulls in cargo-platform 0.3.x which requires rustc >= 1.91,
# but /work/rust-toolchain.toml pins the workspace to 1.88.0. Install with an
# explicit +stable override so the workspace pin is ignored for this tool.
if ! command -v wasm-pack >/dev/null 2>&1; then
  rustup self update || true
  rustup toolchain install stable
  CARGO_HOME="${CARGO_HOME:-/usr/local/cargo}" cargo +stable install wasm-pack
fi

# Install emulator web dependencies for the first `cargo xtask emu` run.
if [ -f /work/device/emulator/web/package-lock.json ] && [ ! -d /work/device/emulator/web/node_modules ]; then
  (cd /work/device/emulator/web && npm ci)
fi

# Keep git global config in a persistent mounted directory.
mkdir -p "${HOME}/.config/git"
if [ ! -f "${HOME}/.config/git/config" ]; then
  touch "${HOME}/.config/git/config"
fi
if [ -f "${HOME}/.gitconfig" ] && [ ! -s "${HOME}/.config/git/config" ]; then
  cp "${HOME}/.gitconfig" "${HOME}/.config/git/config"
fi

# Persisted SSH directory should keep secure permissions for OpenSSH.
mkdir -p "${HOME}/.ssh"
chmod 700 "${HOME}/.ssh"
find "${HOME}/.ssh" -type f -name "id_*" -exec chmod 600 {} \;

# Android companion toolchain (JDK + SDK). Idempotent — skips if already installed.
ANDROID_SETUP="/work/infra/devcontainer/scripts/install-android-toolchain.sh"
if [ -f "${ANDROID_SETUP}" ]; then
  bash "${ANDROID_SETUP}"
fi
