// Companion-web i18n runtime. Loads the catalogs generated by
// `cargo xtask i18n-gen`, exposes `t(key, values?)`, and tracks the active
// locale. The active locale is derived from:
//   1. CompanionSettings.language if set to a concrete locale
//   2. otherwise navigator.languages → first match against shipped locales
//   3. otherwise the source locale (`en`)
//
// Components subscribe through MobX-aware helpers so locale changes
// re-render the UI.

import arMessages from "./messages/ar.json";
import bnMessages from "./messages/bn.json";
import deMessages from "./messages/de.json";
import enMessages from "./messages/en.json";
import esMessages from "./messages/es.json";
import faMessages from "./messages/fa.json";
import fiMessages from "./messages/fi.json";
import frMessages from "./messages/fr.json";
import hiMessages from "./messages/hi.json";
import idMessages from "./messages/id.json";
import jaMessages from "./messages/ja.json";
import mrMessages from "./messages/mr.json";
import pcmMessages from "./messages/pcm.json";
import ptMessages from "./messages/pt.json";
import ruMessages from "./messages/ru.json";
import urMessages from "./messages/ur.json";
import zhMessages from "./messages/zh.json";
import { formatMessage, type MessageValues } from "./messageFormat.js";

export type AppLanguage =
  | "system"
  | "ar" | "bn" | "de" | "en" | "es" | "fa" | "fi" | "fr"
  | "hi" | "id" | "ja" | "mr" | "pcm" | "pt" | "ru" | "ur" | "zh";
export type DistanceUnit = "system" | "metric" | "imperial";

export const SUPPORTED_LOCALES = [
  "ar", "bn", "de", "en", "es", "fa", "fi", "fr",
  "hi", "id", "ja", "mr", "pcm", "pt", "ru", "ur", "zh",
] as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];

const CATALOGS: Record<Locale, Record<string, string>> = {
  ar: arMessages, bn: bnMessages, de: deMessages, en: enMessages,
  es: esMessages, fa: faMessages, fi: fiMessages, fr: frMessages,
  hi: hiMessages, id: idMessages, ja: jaMessages, mr: mrMessages,
  pcm: pcmMessages, pt: ptMessages, ru: ruMessages, ur: urMessages,
  zh: zhMessages,
} as Record<Locale, Record<string, string>>;

/** Right-to-left scripts. Mirror in catalog.config.json:localeOptions.
 *  Drives `<html dir="rtl">` and any layout helpers. */
const RTL_LOCALES: ReadonlySet<Locale> = new Set<Locale>(["ar", "fa", "ur"]);

export function isRtlLocale(locale: Locale): boolean {
  return RTL_LOCALES.has(locale);
}

/** Native-language picker labels. Always presented in the language's own
 *  native form regardless of the active locale, matching iOS/Android
 *  system-language pickers. Not put in the catalog because translating
 *  these would defeat the convention. */
export const NATIVE_LANGUAGE_NAMES: Record<Locale, string> = {
  ar: "العربية",
  bn: "বাংলা",
  de: "Deutsch",
  en: "English",
  es: "Español",
  fa: "فارسی",
  fi: "Suomi",
  fr: "Français",
  hi: "हिन्दी",
  id: "Bahasa Indonesia",
  ja: "日本語",
  mr: "मराठी",
  pcm: "Naijá",
  pt: "Português",
  ru: "Русский",
  ur: "اردو",
  zh: "中文",
};

let activeLocale: Locale = "en";

export function getActiveLocale(): Locale {
  return activeLocale;
}

export function setActiveLocale(locale: Locale): void {
  activeLocale = locale;
  applyDocumentDirection(locale);
}

/** Apply `<html dir="rtl|ltr">` so CSS logical properties (margin-inline-start,
 *  padding-inline-end, etc.) flip correctly for RTL languages. SSR-safe. */
function applyDocumentDirection(locale: Locale): void {
  if (typeof document === "undefined") return;
  document.documentElement.dir = isRtlLocale(locale) ? "rtl" : "ltr";
  document.documentElement.lang = locale;
}

/**
 * Resolve the runtime locale given a user preference. Returns the first
 * shipped locale that matches; falls back to `en`.
 */
export function resolveLocale(language: AppLanguage): Locale {
  if (language !== "system") return language;
  const candidates =
    typeof navigator !== "undefined"
      ? (navigator.languages ?? [navigator.language ?? "en"])
      : ["en"];
  for (const tag of candidates) {
    const primary = tag.split("-")[0]?.toLowerCase();
    if (primary && (SUPPORTED_LOCALES as readonly string[]).includes(primary)) {
      return primary as Locale;
    }
  }
  return "en";
}

/**
 * Resolve the active distance unit given the user preference. `"system"`
 * infers from navigator.language (en-US/en-LR/my → imperial; everything
 * else → metric — matches the Apple/Android default for navigation apps).
 */
export function resolveDistanceUnit(
  preference: DistanceUnit,
  locale: Locale,
): "metric" | "imperial" {
  if (preference === "metric" || preference === "imperial") return preference;
  if (typeof navigator !== "undefined") {
    const tag = navigator.language ?? "en";
    const lower = tag.toLowerCase();
    if (lower.startsWith("en-us") || lower.startsWith("en-lr") || lower.startsWith("my")) {
      return "imperial";
    }
  }
  void locale;
  return "metric";
}

/**
 * Translate `key` for the active locale, formatting any ICU placeholders
 * with `values`. Falls back to the EN catalog when the key is missing
 * from the active locale, then to the key itself.
 */
export function t(key: string, values?: MessageValues): string {
  const template =
    CATALOGS[activeLocale][key] ?? CATALOGS.en[key] ?? key;
  if (!values || Object.keys(values).length === 0) return template;
  try {
    return formatMessage(template, values, activeLocale);
  } catch {
    return template;
  }
}

/**
 * Translate using a specific locale instead of the active one — used by
 * parity tests that need to render English regardless of runtime state.
 */
export function tIn(locale: Locale, key: string, values?: MessageValues): string {
  const template = CATALOGS[locale][key] ?? CATALOGS.en[key] ?? key;
  if (!values || Object.keys(values).length === 0) return template;
  try {
    return formatMessage(template, values, locale);
  } catch {
    return template;
  }
}
