// Companion-web i18n runtime. Loads the catalogs generated by
// `cargo xtask i18n-gen`, exposes `t(key, values?)`, and tracks the active
// locale. The active locale is derived from:
//   1. CompanionSettings.language if set to a concrete locale
//   2. otherwise navigator.languages → first match against shipped locales
//   3. otherwise the source locale (`en`)
//
// Components subscribe through MobX-aware helpers so locale changes
// re-render the UI.

import enMessages from "./messages/en.json";
import fiMessages from "./messages/fi.json";
import { formatMessage, type MessageValues } from "./messageFormat.js";

export type AppLanguage = "system" | "en" | "fi";
export type DistanceUnit = "system" | "metric" | "imperial";

export const SUPPORTED_LOCALES = ["en", "fi"] as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];

const CATALOGS: Record<Locale, Record<string, string>> = {
  en: enMessages as Record<string, string>,
  fi: fiMessages as Record<string, string>,
};

let activeLocale: Locale = "en";

export function getActiveLocale(): Locale {
  return activeLocale;
}

export function setActiveLocale(locale: Locale): void {
  activeLocale = locale;
}

/**
 * Resolve the runtime locale given a user preference. Returns the first
 * shipped locale that matches; falls back to `en`.
 */
export function resolveLocale(language: AppLanguage): Locale {
  if (language === "en" || language === "fi") return language;
  const candidates =
    typeof navigator !== "undefined"
      ? (navigator.languages ?? [navigator.language ?? "en"])
      : ["en"];
  for (const tag of candidates) {
    const primary = tag.split("-")[0]?.toLowerCase();
    if (primary && (SUPPORTED_LOCALES as readonly string[]).includes(primary)) {
      return primary as Locale;
    }
  }
  return "en";
}

/**
 * Resolve the active distance unit given the user preference. `"system"`
 * infers from navigator.language (en-US/en-LR/my → imperial; everything
 * else → metric — matches the Apple/Android default for navigation apps).
 */
export function resolveDistanceUnit(
  preference: DistanceUnit,
  locale: Locale,
): "metric" | "imperial" {
  if (preference === "metric" || preference === "imperial") return preference;
  if (typeof navigator !== "undefined") {
    const tag = navigator.language ?? "en";
    const lower = tag.toLowerCase();
    if (lower.startsWith("en-us") || lower.startsWith("en-lr") || lower.startsWith("my")) {
      return "imperial";
    }
  }
  void locale;
  return "metric";
}

/**
 * Translate `key` for the active locale, formatting any ICU placeholders
 * with `values`. Falls back to the EN catalog when the key is missing
 * from the active locale, then to the key itself.
 */
export function t(key: string, values?: MessageValues): string {
  const template =
    CATALOGS[activeLocale][key] ?? CATALOGS.en[key] ?? key;
  if (!values || Object.keys(values).length === 0) return template;
  try {
    return formatMessage(template, values, activeLocale);
  } catch {
    return template;
  }
}

/**
 * Translate using a specific locale instead of the active one — used by
 * parity tests that need to render English regardless of runtime state.
 */
export function tIn(locale: Locale, key: string, values?: MessageValues): string {
  const template = CATALOGS[locale][key] ?? CATALOGS.en[key] ?? key;
  if (!values || Object.keys(values).length === 0) return template;
  try {
    return formatMessage(template, values, locale);
  } catch {
    return template;
  }
}
